### ISSUE TITLE
examples for filtering table names and views

### ISSUE THREAD

**Issue by barbalex** [nsingla/dbdiagrams#2]
This can probably be done by adjusting the sql query in settings.conf, so sorry for bugging you. But maybe others could profit from some examples in the readme too.

My database contains lots of simple lookup tables name `something_werte`. It would help a lot to not include tables whose name ends with `_werte`.

Also it would help if views could be excluded.

I will try to achieve this myself. If I manage, I'll add it to this issue or maybe create a pull request for the readme file.

**Comment by nsingla** [comment]
great point, I can add these for sure. I can add parameter in conf, to have an exclusion list that matches with names alike and a setting to exclude views.

Also I realize I should have a setting for table_schema as well.

**Comment by barbalex** [comment]
Sounds great. Just know that I am not sitting here wringing my hands until this lands. Don't feel obliged to prioritize this.

I simply have been keeping an eye open for a tool to create diagrams that suits me better than the others I have so far found.

**Comment by nsingla** [comment]
I've added options in ```settings.conf``` for specifying table_schema and excluding views and certain tables. Let me know if it works !

**Comment by barbalex** [comment]
Gorgeous!
